# Generated by Django 6.0.4 on 2026-05-04 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=20, unique=True)),
                ('ten_mon', models.CharField(max_length=100)),
                ('he_so', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='giaovien',
            name='chuyen_mon',
        ),
        migrations.AddField(
            model_name='giaovien',
            name='to_bo_mon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='giaovien',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giao_vien_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hocsinh',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoc_sinh_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ho_ten',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='trang_thai',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(choices=[('quan_ly', 'Quản Lý'), ('giao_vien', 'Giáo Viên'), ('hoc_sinh', 'Học Sinh')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='giaovien',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hocsinh',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nguoidung',
            table=None,
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=20, unique=True)),
                ('ten_lop', models.CharField(max_length=50)),
                ('nam_hoc', models.CharField(max_length=20)),
                ('giao_vien_chu_nhiem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_chu_nhiem', to='core.giaovien')),
            ],
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='lop_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_sach_hoc_sinh', to='core.lophoc'),
        ),
        migrations.CreateModel(
            name='BangDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ky', models.IntegerField(choices=[(1, 'Học kỳ 1'), (2, 'Học kỳ 2')])),
                ('diem_15p', models.FloatField(blank=True, null=True)),
                ('diem_giua_ky', models.FloatField(blank=True, null=True)),
                ('diem_cuoi_ky', models.FloatField(blank=True, null=True)),
                ('hoc_sinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_diem', to='core.hocsinh')),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diem_cac_lop', to='core.monhoc')),
            ],
            options={
                'unique_together': {('hoc_sinh', 'mon_hoc', 'hoc_ky')},
            },
        ),
    ]
