# Generated by Django 6.0.4 on 2026-06-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_monhoc_alter_nguoidung_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGiaChuyenCan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_danh_gia', models.DateField(auto_now_add=True)),
                ('loai_vi_pham', models.CharField(choices=[('vang_phep', 'Vắng có phép'), ('vang_khong_phep', 'Vắng không phép'), ('tre', 'Đi trễ'), ('vi_pham_noi_quy', 'Vi phạm nội quy')], max_length=20)),
                ('chi_tiet', models.TextField(help_text='Ghi chú chi tiết lỗi hoặc lý do')),
                ('giao_vien_danh_gia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.giaovien')),
                ('hoc_sinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_chuyen_can', to='core.hocsinh')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lophoc')),
            ],
        ),
        migrations.CreateModel(
            name='ThoiKhoaBieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu_trong_tuan', models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7')])),
                ('tiet_hoc', models.IntegerField()),
                ('giao_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_day', to='core.giaovien')),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoi_khoa_bieu', to='core.lophoc')),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.monhoc')),
            ],
            options={
                'unique_together': {('giao_vien', 'thu_trong_tuan', 'tiet_hoc')},
            },
        ),
    ]
