# Generated by Django 6.0.5 on 2026-06-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_danhgiachuyencan_thoikhoabieu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DanhGiaChuyenCan',
        ),
    ]
