# Generated by Django 6.0.5 on 2026-06-03 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_danhgiachuyencan'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoikhoabieu',
            name='ma_tkb',
            field=models.CharField(default=1, help_text='VD: TKB_KHOI10_THANG6_2026', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thoikhoabieu',
            name='ngay_hoc',
            field=models.DateField(default=datetime.date(2026, 6, 3)),
            preserve_default=False,
        ),
    ]
