# Generated by Django 6.0.5 on 2026-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_thoikhoabieu_ma_tkb_thoikhoabieu_ngay_hoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaovien',
            name='bo_mon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
