# Generated by Django 6.0.5 on 2026-06-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_giaovien_bo_mon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thoikhoabieu',
            unique_together={('giao_vien', 'ngay_hoc', 'tiet_hoc')},
        ),
    ]
